"""
Desktop Runtime Port Interfaces

Port layer (protocols) for Phase 4 Milestone 6.
Every desktop subsystem behind these ports is replaceable.
"""

from __future__ import annotations

from collections.abc import Sequence
from typing import Any, Protocol, runtime_checkable

from agentic_os.domain.desktop import (
    ClipboardContent,
    DesktopConfig,
    DesktopDiagnosticsInfo,
    DesktopNotification,
    DesktopPerformanceMetrics,
    DesktopRuntimeState,
    DialogConfig,
    DialogResult,
    PanelConfig,
    ProcessInfo,
    TabInfo,
    TerminalConfig,
    TerminalInfo,
    ThemeMode,
    WindowConfig,
    WindowInfo,
    Workspace,
    WorkspaceLayout,
)


@runtime_checkable
class DesktopRuntimePort(Protocol):
    """Top-level desktop runtime interface."""

    async def start(self) -> None: ...
    async def stop(self) -> None: ...
    async def get_state(self) -> DesktopRuntimeState: ...
    async def get_status(self) -> str: ...
    async def restart(self) -> None: ...


@runtime_checkable
class DesktopWindowPort(Protocol):
    """Native window management interface."""

    async def create_window(self, config: WindowConfig) -> WindowInfo: ...
    async def close_window(self, window_id: str) -> bool: ...
    async def get_window(self, window_id: str) -> WindowInfo | None: ...
    async def list_windows(self) -> Sequence[WindowInfo]: ...
    async def focus_window(self, window_id: str) -> bool: ...
    async def minimize_window(self, window_id: str) -> bool: ...
    async def maximize_window(self, window_id: str) -> bool: ...
    async def restore_window(self, window_id: str) -> bool: ...
    async def set_window_title(self, window_id: str, title: str) -> bool: ...
    async def set_window_size(self, window_id: str, width: int, height: int) -> bool: ...
    async def set_window_position(self, window_id: str, x: int, y: int) -> bool: ...
    async def enter_fullscreen(self, window_id: str) -> bool: ...
    async def exit_fullscreen(self, window_id: str) -> bool: ...
    async def is_window_focused(self, window_id: str) -> bool: ...
    async def show_window(self, window_id: str) -> bool: ...
    async def hide_window(self, window_id: str) -> bool: ...


@runtime_checkable
class DesktopNotificationPort(Protocol):
    """Native notification interface."""

    async def send_notification(self, notification: DesktopNotification) -> DesktopNotification: ...
    async def dismiss_notification(self, notification_id: str) -> bool: ...
    async def list_notifications(self) -> Sequence[DesktopNotification]: ...
    async def clear_notifications(self) -> None: ...
    async def get_notification(self, notification_id: str) -> DesktopNotification | None: ...


@runtime_checkable
class DesktopFilePort(Protocol):
    """Native file dialog and file system interface."""

    async def open_file_dialog(self, config: DialogConfig) -> DialogResult: ...
    async def save_file_dialog(self, config: DialogConfig) -> DialogResult: ...
    async def select_folder_dialog(self, config: DialogConfig) -> DialogResult: ...
    async def read_file(self, path: str) -> bytes: ...
    async def write_file(self, path: str, data: bytes) -> bool: ...
    async def file_exists(self, path: str) -> bool: ...
    async def get_file_info(self, path: str) -> dict[str, Any]: ...


@runtime_checkable
class DesktopClipboardPort(Protocol):
    """Native clipboard interface."""

    async def read_text(self) -> str: ...
    async def write_text(self, text: str) -> None: ...
    async def read_html(self) -> str | None: ...
    async def write_html(self, html: str) -> None: ...
    async def read_files(self) -> list[str]: ...
    async def write_files(self, paths: list[str]) -> None: ...
    async def clear(self) -> None: ...
    async def get_content(self) -> ClipboardContent: ...
    async def set_content(self, content: ClipboardContent) -> None: ...


@runtime_checkable
class DesktopTerminalPort(Protocol):
    """Native terminal interface."""

    async def open_terminal(self, config: TerminalConfig) -> TerminalInfo: ...
    async def close_terminal(self, terminal_id: str) -> bool: ...
    async def list_terminals(self) -> Sequence[TerminalInfo]: ...
    async def get_terminal(self, terminal_id: str) -> TerminalInfo | None: ...
    async def write_to_terminal(self, terminal_id: str, data: str) -> bool: ...
    async def resize_terminal(self, terminal_id: str, rows: int, cols: int) -> bool: ...


@runtime_checkable
class DesktopProcessPort(Protocol):
    """Native process management interface."""

    async def list_processes(self) -> Sequence[ProcessInfo]: ...
    async def get_process(self, pid: int) -> ProcessInfo | None: ...
    async def kill_process(self, pid: int, force: bool = False) -> bool: ...
    async def spawn_process(
        self, command: str, args: list[str] | None = None, cwd: str | None = None
    ) -> ProcessInfo: ...


@runtime_checkable
class DesktopLoggingPort(Protocol):
    """Desktop-native logging interface."""

    async def log_info(self, message: str, **kwargs: Any) -> None: ...
    async def log_warning(self, message: str, **kwargs: Any) -> None: ...
    async def log_error(self, message: str, **kwargs: Any) -> None: ...
    async def log_debug(self, message: str, **kwargs: Any) -> None: ...
    async def get_logs(
        self, level: str | None = None, limit: int = 100, offset: int = 0
    ) -> Sequence[dict[str, Any]]: ...
    async def clear_logs(self) -> None: ...


@runtime_checkable
class DesktopConfigurationPort(Protocol):
    """Desktop configuration interface."""

    async def get_config(self) -> DesktopConfig: ...
    async def update_config(self, config: DesktopConfig) -> DesktopConfig: ...
    async def reset_config(self) -> DesktopConfig: ...
    async def set_theme(self, theme: ThemeMode) -> None: ...
    async def get_theme(self) -> ThemeMode: ...
    async def get_setting(self, key: str) -> Any: ...
    async def set_setting(self, key: str, value: Any) -> None: ...


@runtime_checkable
class DesktopDiagnosticsPort(Protocol):
    """Desktop diagnostics interface."""

    async def get_diagnostics(self) -> DesktopDiagnosticsInfo: ...
    async def get_performance(self) -> DesktopPerformanceMetrics: ...
    async def run_diagnostics(self) -> dict[str, Any]: ...
    async def check_health(self) -> dict[str, Any]: ...


@runtime_checkable
class DesktopPerformancePort(Protocol):
    """Desktop performance monitoring interface."""

    async def get_metrics(self) -> DesktopPerformanceMetrics: ...
    async def get_metric_history(self, metric: str, limit: int = 60) -> Sequence[float]: ...
    async def start_monitoring(self, interval_seconds: float = 5.0) -> None: ...
    async def stop_monitoring(self) -> None: ...


@runtime_checkable
class DesktopWorkspacePort(Protocol):
    """Desktop workspace management interface."""

    async def create_workspace(self, name: str) -> Workspace: ...
    async def get_workspace(self, workspace_id: str) -> Workspace | None: ...
    async def list_workspaces(self) -> Sequence[Workspace]: ...
    async def update_workspace(self, workspace: Workspace) -> Workspace: ...
    async def delete_workspace(self, workspace_id: str) -> bool: ...
    async def switch_workspace(self, workspace_id: str) -> Workspace: ...
    async def get_active_workspace(self) -> Workspace | None: ...
    async def get_workspace_layout(self, workspace_id: str) -> WorkspaceLayout | None: ...
    async def update_workspace_layout(
        self, workspace_id: str, layout: WorkspaceLayout
    ) -> WorkspaceLayout: ...
    async def add_tab(self, workspace_id: str, tab: TabInfo) -> TabInfo: ...
    async def remove_tab(self, workspace_id: str, tab_id: str) -> bool: ...
    async def activate_tab(self, workspace_id: str, tab_id: str) -> bool: ...
    async def add_panel(self, workspace_id: str, panel: PanelConfig) -> PanelConfig: ...
    async def remove_panel(self, workspace_id: str, panel_id: str) -> bool: ...


__all__ = [
    "DesktopRuntimePort",
    "DesktopWindowPort",
    "DesktopNotificationPort",
    "DesktopFilePort",
    "DesktopClipboardPort",
    "DesktopTerminalPort",
    "DesktopProcessPort",
    "DesktopLoggingPort",
    "DesktopConfigurationPort",
    "DesktopDiagnosticsPort",
    "DesktopPerformancePort",
    "DesktopWorkspacePort",
]
