"""
Learning & Optimization Port Interfaces

Port layer (protocols) for Phase 4 Milestone 5.
Every subsystem behind these ports is replaceable without touching callers.
"""

from __future__ import annotations

from collections.abc import Sequence
from typing import Any, Protocol, runtime_checkable

from agentic_os.domain.learning import (
    Benchmark,
    CostMetrics,
    Evaluation,
    ExecutionHistory,
    ExecutionStatistics,
    Experiment,
    FailureAnalysis,
    LatencyMetrics,
    LearningMetrics,
    LearningProfile,
    OptimizationPolicy,
    OptimizationRecommendation,
    OptimizationResult,
    OptimizationTarget,
    PerformanceProfile,
    QualityMetrics,
    Recommendation,
    RecommendationStatus,
    RoutingDecision,
)


@runtime_checkable
class LearningPort(Protocol):
    """Main learning interface — data collection, analysis, and model management."""

    async def create_profile(self, profile: LearningProfile) -> LearningProfile: ...
    async def get_profile(self, profile_id: str) -> LearningProfile | None: ...
    async def list_profiles(self) -> Sequence[LearningProfile]: ...
    async def update_profile(self, profile: LearningProfile) -> LearningProfile: ...
    async def delete_profile(self, profile_id: str) -> None: ...
    async def record_execution(self, history: ExecutionHistory) -> ExecutionHistory: ...
    async def get_execution_history(self, execution_id: str) -> ExecutionHistory | None: ...
    async def list_execution_history(
        self, limit: int = 100, offset: int = 0, **filters: Any
    ) -> Sequence[ExecutionHistory]: ...
    async def analyze_executions(self, history_ids: tuple[str, ...]) -> ExecutionStatistics: ...
    async def compute_learning_metrics(
        self, period_start: str | None = None, period_end: str | None = None
    ) -> LearningMetrics: ...


@runtime_checkable
class OptimizationPort(Protocol):
    """Optimization interface — applying and tracking optimizations."""

    async def optimize(
        self, target: OptimizationTarget, config: dict[str, Any]
    ) -> OptimizationResult: ...
    async def get_result(self, result_id: str) -> OptimizationResult | None: ...
    async def list_results(
        self, limit: int = 50, **filters: Any
    ) -> Sequence[OptimizationResult]: ...
    async def rollback(self, result_id: str) -> OptimizationResult: ...
    async def get_effectiveness(self) -> float: ...


@runtime_checkable
class BenchmarkPort(Protocol):
    """Benchmark interface — running and tracking benchmarks."""

    async def create_benchmark(self, benchmark: Benchmark) -> Benchmark: ...
    async def get_benchmark(self, benchmark_id: str) -> Benchmark | None: ...
    async def list_benchmarks(self) -> Sequence[Benchmark]: ...
    async def run_benchmark(self, benchmark_id: str) -> Benchmark: ...
    async def compare(self, benchmark_id: str) -> Benchmark: ...
    async def delete_benchmark(self, benchmark_id: str) -> None: ...


@runtime_checkable
class EvaluationPort(Protocol):
    """Evaluation interface — scoring and pass/fail assessment."""

    async def evaluate(
        self, target_id: str, target_type: str, metrics: dict[str, float]
    ) -> Evaluation: ...
    async def get_evaluation(self, evaluation_id: str) -> Evaluation | None: ...
    async def list_evaluations(self, target_id: str) -> Sequence[Evaluation]: ...


@runtime_checkable
class RecommendationPort(Protocol):
    """Recommendation interface — generating and managing recommendations."""

    async def generate_recommendation(
        self, category: str, context: dict[str, Any]
    ) -> Recommendation: ...
    async def get_recommendation(self, recommendation_id: str) -> Recommendation | None: ...
    async def list_recommendations(
        self, status: RecommendationStatus | None = None, limit: int = 50
    ) -> Sequence[Recommendation]: ...
    async def apply_recommendation(self, recommendation_id: str) -> Recommendation: ...
    async def dismiss_recommendation(self, recommendation_id: str) -> Recommendation: ...


@runtime_checkable
class ExperimentPort(Protocol):
    """Experiment interface — A/B testing, canary, controlled rollouts."""

    async def create_experiment(self, experiment: Experiment) -> Experiment: ...
    async def get_experiment(self, experiment_id: str) -> Experiment | None: ...
    async def list_experiments(self) -> Sequence[Experiment]: ...
    async def start_experiment(self, experiment_id: str) -> Experiment: ...
    async def complete_experiment(self, experiment_id: str) -> Experiment: ...
    async def rollback_experiment(self, experiment_id: str) -> Experiment: ...
    async def delete_experiment(self, experiment_id: str) -> None: ...


@runtime_checkable
class RoutingOptimizationPort(Protocol):
    """Routing-specific optimization interface."""

    async def analyze_routing(self) -> Sequence[OptimizationRecommendation]: ...
    async def optimize_routing(self, recommendation_id: str) -> RoutingDecision: ...
    async def get_routing_history(self, limit: int = 100) -> Sequence[RoutingDecision]: ...
    async def get_routing_stats(self) -> dict[str, Any]: ...


@runtime_checkable
class PerformanceOptimizationPort(Protocol):
    """Performance-specific optimization interface."""

    async def profile_performance(self, target_id: str, target_type: str) -> PerformanceProfile: ...
    async def analyze_performance(self) -> Sequence[OptimizationRecommendation]: ...
    async def optimize_performance(self, recommendation_id: str) -> OptimizationResult: ...
    async def get_performance_trends(self) -> dict[str, Any]: ...


@runtime_checkable
class TelemetryLearningPort(Protocol):
    """Telemetry feed — ingests platform metrics for learning."""

    async def ingest_execution_metrics(self, metrics: dict[str, Any]) -> None: ...
    async def ingest_performance_metrics(self, metrics: dict[str, Any]) -> None: ...
    async def ingest_cost_metrics(self, metrics: dict[str, Any]) -> None: ...
    async def ingest_failure_metrics(self, metrics: dict[str, Any]) -> None: ...
    async def get_latency_metrics(
        self, period_start: str | None = None, period_end: str | None = None
    ) -> LatencyMetrics: ...
    async def get_cost_metrics(
        self, period_start: str | None = None, period_end: str | None = None
    ) -> CostMetrics: ...
    async def get_quality_metrics(
        self, period_start: str | None = None, period_end: str | None = None
    ) -> QualityMetrics: ...
    async def get_failure_analysis(
        self, period_start: str | None = None, period_end: str | None = None
    ) -> FailureAnalysis: ...


@runtime_checkable
class PolicyPort(Protocol):
    """Policy interface — managing optimization policies."""

    async def create_policy(self, policy: OptimizationPolicy) -> OptimizationPolicy: ...
    async def get_policy(self, policy_id: str) -> OptimizationPolicy | None: ...
    async def list_policies(self) -> Sequence[OptimizationPolicy]: ...
    async def update_policy(self, policy: OptimizationPolicy) -> OptimizationPolicy: ...
    async def delete_policy(self, policy_id: str) -> None: ...
    async def check_policy(self, target: OptimizationTarget, context: dict[str, Any]) -> bool: ...


__all__ = [
    "LearningPort",
    "OptimizationPort",
    "BenchmarkPort",
    "EvaluationPort",
    "RecommendationPort",
    "ExperimentPort",
    "RoutingOptimizationPort",
    "PerformanceOptimizationPort",
    "TelemetryLearningPort",
    "PolicyPort",
]
