"""Phase 17 — Evolution domain models.

Pure data structures for autonomous agent evolution, self-construction,
and continuous improvement.

All additive — does not modify any existing domain model.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from datetime import UTC, datetime
from enum import StrEnum
from typing import Any
from uuid import uuid4


def _now_iso() -> str:
    return datetime.now(UTC).isoformat()


def _new_id(prefix: str = "") -> str:
    return f"{prefix}{uuid4().hex[:12]}" if prefix else uuid4().hex[:12]


# ── Improvement Lifecycle ──────────────────────────────────────────────


class ImprovementStatus(StrEnum):
    """Lifecycle states for an improvement proposal."""

    PROPOSED = "proposed"  # just created, not yet validated
    VALIDATING = "validating"  # safety validation in progress
    VALIDATED = "validated"  # passed all safety checks
    APPROVED = "approved"  # approved for execution
    SCHEDULED = "scheduled"  # scheduled by ImprovementScheduler
    EXECUTING = "executing"  # execution simulation in progress
    APPLIED = "applied"  # successfully applied
    REJECTED = "rejected"  # failed safety validation
    ROLLED_BACK = "rolled_back"  # applied then reverted
    SUPERSEDED = "superseded"  # replaced by a newer improvement


class ImprovementType(StrEnum):
    """What kind of improvement this is."""

    CAPABILITY_EXPANSION = "capability_expansion"
    REFACTORING = "refactoring"
    PERFORMANCE_OPTIMIZATION = "performance_optimization"
    NEW_AGENT = "new_agent"
    NEW_WORKFLOW = "new_workflow"
    NEW_PLANNER = "new_planner"
    NEW_TOOL = "new_tool"
    NEW_ORCHESTRATOR = "new_orchestrator"
    NEW_STRATEGY = "new_strategy"
    CONFIGURATION_TUNING = "configuration_tuning"
    ROUTING_OPTIMIZATION = "routing_optimization"


class ImprovementPriority(StrEnum):
    """Priority level for scheduling."""

    CRITICAL = "critical"
    HIGH = "high"
    MEDIUM = "medium"
    LOW = "low"
    BACKGROUND = "background"


# ── Improvement Proposal ───────────────────────────────────────────────


@dataclass
class ImprovementProposal:
    """A proposed improvement to the AgenticOS platform.

    Generated by ImprovementEngine from:
      - ecosystem.evolution_engine recommendations (Phase 15)
      - cognitive.improvement_planner proposals (Phase 12)
      - performance metrics analysis
      - capability gap detection
    """

    id: str = field(default_factory=lambda: _new_id("imp-"))
    type: ImprovementType = ImprovementType.PERFORMANCE_OPTIMIZATION
    title: str = ""
    description: str = ""
    rationale: str = ""
    priority: ImprovementPriority = ImprovementPriority.MEDIUM
    status: ImprovementStatus = ImprovementStatus.PROPOSED
    # Source tracking
    source: str = ""  # "ecosystem" | "cognitive" | "performance" | "manual"
    source_recommendation_id: str = ""
    # Target
    target_module: str = ""
    target_capability: str = ""
    # Impact estimates (0.0-1.0)
    expected_impact: float = 0.0
    confidence: float = 0.0
    risk_score: float = 0.0
    # Implementation plan
    implementation_plan: dict[str, Any] = field(default_factory=dict)
    dependency_graph: dict[str, Any] = field(default_factory=dict)
    rollout_plan: dict[str, Any] = field(default_factory=dict)
    rollback_plan: dict[str, Any] = field(default_factory=dict)
    # Safety validation results
    safety_validation: dict[str, Any] = field(default_factory=dict)
    regression_prediction: dict[str, Any] = field(default_factory=dict)
    # Execution tracking
    scheduled_at: str = ""
    executed_at: str = ""
    applied_at: str = ""
    rolled_back_at: str = ""
    # Evidence
    evidence: dict[str, Any] = field(default_factory=dict)
    created_at: str = field(default_factory=_now_iso)
    updated_at: str = field(default_factory=_now_iso)

    def to_dict(self) -> dict[str, Any]:
        return {
            "id": self.id,
            "type": self.type.value,
            "title": self.title,
            "description": self.description,
            "rationale": self.rationale,
            "priority": self.priority.value,
            "status": self.status.value,
            "source": self.source,
            "source_recommendation_id": self.source_recommendation_id,
            "target_module": self.target_module,
            "target_capability": self.target_capability,
            "expected_impact": round(self.expected_impact, 3),
            "confidence": round(self.confidence, 3),
            "risk_score": round(self.risk_score, 3),
            "implementation_plan": dict(self.implementation_plan),
            "dependency_graph": dict(self.dependency_graph),
            "rollout_plan": dict(self.rollout_plan),
            "rollback_plan": dict(self.rollback_plan),
            "safety_validation": dict(self.safety_validation),
            "regression_prediction": dict(self.regression_prediction),
            "scheduled_at": self.scheduled_at,
            "executed_at": self.executed_at,
            "applied_at": self.applied_at,
            "rolled_back_at": self.rolled_back_at,
            "evidence": dict(self.evidence),
            "created_at": self.created_at,
            "updated_at": self.updated_at,
        }


# ── Safety Validation ─────────────────────────────────────────────────


class ValidationCheckType(StrEnum):
    """Types of safety checks an improvement must pass."""

    ARCHITECTURE = "architecture"
    DEPENDENCY = "dependency"
    API_COMPATIBILITY = "api_compatibility"
    REGRESSION_PREDICTION = "regression_prediction"
    SECURITY = "security"
    PERFORMANCE = "performance"


class ValidationCheckResult(StrEnum):
    PASS = "pass"
    FAIL = "fail"
    WARNING = "warning"
    SKIP = "skip"


@dataclass
class ValidationCheck:
    """A single safety validation check."""

    type: ValidationCheckType
    result: ValidationCheckResult = ValidationCheckResult.SKIP
    score: float = 0.0  # 0.0-1.0
    message: str = ""
    details: dict[str, Any] = field(default_factory=dict)
    duration_ms: float = 0.0
    timestamp: str = field(default_factory=_now_iso)

    def to_dict(self) -> dict[str, Any]:
        return {
            "type": self.type.value,
            "result": self.result.value,
            "score": round(self.score, 3),
            "message": self.message,
            "details": dict(self.details),
            "duration_ms": round(self.duration_ms, 2),
            "timestamp": self.timestamp,
        }


@dataclass
class SafetyValidationReport:
    """Complete safety validation report for an improvement."""

    improvement_id: str
    checks: list[ValidationCheck] = field(default_factory=list)
    overall_result: ValidationCheckResult = ValidationCheckResult.SKIP
    overall_score: float = 0.0
    approved: bool = False
    blocking_issues: list[str] = field(default_factory=list)
    warnings: list[str] = field(default_factory=list)
    created_at: str = field(default_factory=_now_iso)

    def to_dict(self) -> dict[str, Any]:
        return {
            "improvement_id": self.improvement_id,
            "checks": [c.to_dict() for c in self.checks],
            "overall_result": self.overall_result.value,
            "overall_score": round(self.overall_score, 3),
            "approved": self.approved,
            "blocking_issues": list(self.blocking_issues),
            "warnings": list(self.warnings),
            "created_at": self.created_at,
        }


# ── Code Generation Plan ──────────────────────────────────────────────


class GenerationTargetType(StrEnum):
    """What kind of artifact to generate."""

    CAPABILITY = "capability"
    AGENT = "agent"
    WORKFLOW = "workflow"
    PLANNER = "planner"
    TOOL = "tool"
    ORCHESTRATOR = "orchestrator"
    STRATEGY = "strategy"
    MODULE = "module"


@dataclass
class GenerationPlan:
    """A plan for generating a new artifact (NOT the code itself).

    Phase 17 generates PLANS, not executable code. The plan describes
    what should be created, why, and how — but never directly overwrites
    existing production code.
    """

    id: str = field(default_factory=lambda: _new_id("gen-"))
    target_type: GenerationTargetType = GenerationTargetType.MODULE
    name: str = ""
    description: str = ""
    # Blueprint
    blueprint: dict[str, Any] = field(default_factory=dict)
    # Dependencies
    dependencies: list[str] = field(default_factory=list)
    affected_modules: list[str] = field(default_factory=list)
    # Validation
    validation_strategy: dict[str, Any] = field(default_factory=dict)
    # Rollout
    rollout_steps: list[dict[str, Any]] = field(default_factory=list)
    rollback_steps: list[dict[str, Any]] = field(default_factory=list)
    # Status
    status: str = "draft"  # draft | reviewed | approved | generated | rejected
    created_at: str = field(default_factory=_now_iso)

    def to_dict(self) -> dict[str, Any]:
        return {
            "id": self.id,
            "target_type": self.target_type.value,
            "name": self.name,
            "description": self.description,
            "blueprint": dict(self.blueprint),
            "dependencies": list(self.dependencies),
            "affected_modules": list(self.affected_modules),
            "validation_strategy": dict(self.validation_strategy),
            "rollout_steps": list(self.rollout_steps),
            "rollback_steps": list(self.rollback_steps),
            "status": self.status,
            "created_at": self.created_at,
        }


# ── Knowledge Synthesis ───────────────────────────────────────────────


@dataclass
class KnowledgeSynthesis:
    """Synthesized knowledge from historical analysis."""

    id: str = field(default_factory=lambda: _new_id("ks-"))
    topic: str = ""
    summary: str = ""
    key_insights: list[str] = field(default_factory=list)
    patterns: list[dict[str, Any]] = field(default_factory=list)
    recommendations: list[str] = field(default_factory=list)
    confidence: float = 0.0
    sources: list[str] = field(default_factory=list)
    created_at: str = field(default_factory=_now_iso)

    def to_dict(self) -> dict[str, Any]:
        return {
            "id": self.id,
            "topic": self.topic,
            "summary": self.summary,
            "key_insights": list(self.key_insights),
            "patterns": list(self.patterns),
            "recommendations": list(self.recommendations),
            "confidence": round(self.confidence, 3),
            "sources": list(self.sources),
            "created_at": self.created_at,
        }


# ── Evolution Statistics ──────────────────────────────────────────────


@dataclass
class EvolutionStatistics:
    """Aggregate evolution statistics."""

    total_proposals: int = 0
    pending: int = 0
    validated: int = 0
    approved: int = 0
    applied: int = 0
    rejected: int = 0
    rolled_back: int = 0
    generation_plans: int = 0
    knowledge_syntheses: int = 0
    safety_pass_rate: float = 0.0
    average_impact: float = 0.0
    average_risk: float = 0.0
    last_updated: str = field(default_factory=_now_iso)

    def to_dict(self) -> dict[str, Any]:
        return {
            "total_proposals": self.total_proposals,
            "pending": self.pending,
            "validated": self.validated,
            "approved": self.approved,
            "applied": self.applied,
            "rejected": self.rejected,
            "rolled_back": self.rolled_back,
            "generation_plans": self.generation_plans,
            "knowledge_syntheses": self.knowledge_syntheses,
            "safety_pass_rate": round(self.safety_pass_rate, 3),
            "average_impact": round(self.average_impact, 3),
            "average_risk": round(self.average_risk, 3),
            "last_updated": self.last_updated,
        }


# ── System Readiness ──────────────────────────────────────────────────


class SystemReadinessLevel(StrEnum):
    """Overall system readiness for autonomous evolution."""

    BLOCKED = "blocked"  # safety validation failing
    CAUTIOUS = "cautious"  # some warnings, proceed with care
    READY = "ready"  # all clear
    OPTIMIZING = "optimizing"  # actively applying improvements


@dataclass
class SystemReadiness:
    """Live system readiness assessment."""

    level: SystemReadinessLevel = SystemReadinessLevel.READY
    readiness_score: float = 1.0
    active_improvements: int = 0
    pending_validations: int = 0
    regression_risk: float = 0.0
    last_applied: str = ""
    last_rollback: str = ""
    issues: list[str] = field(default_factory=list)
    updated_at: str = field(default_factory=_now_iso)

    def to_dict(self) -> dict[str, Any]:
        return {
            "level": self.level.value,
            "readiness_score": round(self.readiness_score, 3),
            "active_improvements": self.active_improvements,
            "pending_validations": self.pending_validations,
            "regression_risk": round(self.regression_risk, 3),
            "last_applied": self.last_applied,
            "last_rollback": self.last_rollback,
            "issues": list(self.issues),
            "updated_at": self.updated_at,
        }
